### ISSUE TITLE
enable skipping SSL cert installation

### ISSUE THREAD

**Issue by mrozati** [wcm-io-devops/ansible-conga-aem-dispatcher#13]
Usecase: SSL certificates are already provisioned by platform provider and will be also updated by them. In this case it should be possible to skip the task `Copy SSL files.`

ideas: 
1. tag this task e.g. with `copycerts` to enable skipping it with `--skip-tags`
2. define a CONGA property and use it in a `when` clause

**Comment by tobias-richter** [comment]
@mrozati i reviewed your PR.
This should also be part of the conga-aem-definitions.
