### ISSUE TITLE
Don't use apache2_module on Red Hat derivates

### ISSUE THREAD

**Issue by interatom** [wcm-io-devops/ansible-conga-aem-dispatcher#9]
See [this issue](https://github.com/wcm-io-devops/ansible-role-apache/issues/7). [This](https://github.com/wcm-io-devops/ansible-conga-aem-dispatcher/commit/b10e23eb8b0897786ab5ca61533a4667a1857eaf#diff-ba014a906537266b72c9c4d371ffc9ee) is the relevant commit for this role.

**Comment by tobias-richter** [comment]
@interatom please review the fix from https://github.com/wcm-io-devops/ansible-conga-aem-dispatcher/pull/11

**Comment by tobias-richter** [comment]
I just merged the PR #11. Closing this as fixed.
